name: CI

on:
  push:
    branches: [ main ]
  # pull_request:
  #   branches: [ main ]
  # Allows to run this workflow manually from Github
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
      - uses: actions/setup-node@v2
        with:
          node-version: '14.x'
            
      - name: Install dependencies
      - run: npm i

      - name: Run test
      - run: npm test