name: CI-CD

on:
  push:
    branches: [ main ]
  # pull_request:
  #   branches: [ main ]
  # Allows to run this workflow manually from Github
  workflow_dispatch:

jobs:
  build:
    name: CI - Nodejs Env and Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'

      - name: Install dependencies
        run: npm i

      - name: Run test
        run: npm test

  deploy:
    name: CD - Deploy to Heroku Cloud
    runs-on: ubuntu-latest
    needs: [build] # await build job
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}} # this is a secret key from project
          heroku_app_name: "ci-cd-actions-and-heroku" #Must be unique in Heroku
          heroku_email: "ricardo18acs@gmail.com"